### PR TITLE
fix sendMessage function to push all devices

### PR DESCRIPTION
**Pull request by pongib**
I just use pushwoosh and found your module, it great and very good document. But, I try to use simple function, sendMessage with no specific any device token 

```javascript
module.exports.push = function (req, res, next) {
  var client = new Pushwoosh(pushwooshConfig.appCode, pushwooshConfig.apiToken)

  client.sendMessage('send to all devices', function(err, results) {
     if (err) res.json({ status: 0, msg: err })
     res.json({ status: 1, msg: results })
  })
}
```

Unfortunately, I receive status code 210

```
{
  "status": 1,
  "msg": {
    "description": "Argument error",
    "detail": "Invalid devices list. \"devices\" must be an array.",
    "code": 210
  }
}
```

I try to specific device token it work well, so I decide to view your code and try little change and everything work fine. I read pushwoosh document and see some information about this issue 

```
"devices":[ "dec301908b9ba8df85e57a58e40f96f523f4c2068674f5fe2ba25cdc250a2a41"]
  // Optional. Not more than 1000 tokens in an array. If set, message will only be delivered to the devices in the list. Ignored if the applications group is used. Only lower case for iOS

```

and simple request example that

> Here’s the simple request that will just send a Hello world! push notification to **all subscribers** of the app:

```
{
    "request": {
        "application": "APPLICATION_CODE",
        "auth": "API_ACCESS_TOKEN",
        "notifications": [{
            "send_date": "now", // YYYY-MM-DD HH:mm  OR 'now'
            "ignore_user_timezone": true, // or false
            "content": "Hello world!"
        }]
    }
}
```

I didn't see devices variable in request object. Last, If I wrong, apologize for my newbie :smile: 
FYI: I just have 2 subscribers in my pushwoosh and all of them is test device

### CODE REVIEW

**Comment by auridevil** [comment]
I'm having this problem too

**Comment by nluo** [comment]
hey @pongib thanks for your PR. Sorry for the delays I looked at it before but forgot to merge it. I tested your PR looks good to me just a bit coding formats which I will fix after merging.

**Comment by nluo** [comment]
@auridevil thanks for letting me know. I will merge this fix and will publish to npm.

**Comment by nluo** [comment]
The latest version (1.2.1) with fix has been published to npm. Thanks @pongib again. :smile:

**Pull request merged**
